version: "3"
services:
  app:
    build:
      context: ./app
    restart: always
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
      args:
        - DOMAIN
    restart: always
    # command: /bin/sh -c " && nginx -g 'daemon off;'"
    volumes:
      - letsencrypt-data:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  certbot:
    build:
      context: ./certbot
      args:
        - CLOUDFLARE_API_TOKEN
    environment:
      - DOMAIN=${DOMAIN}
      - WILDCARD_DOMAIN=${WILDCARD_DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - letsencrypt-data:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sh cert.sh; sleep 12h & wait $${!}; done;"
    restart: always

volumes:
  letsencrypt-data:
  https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL
