version: "3"
services:
  nginx:
    image: nginx:1.19.2-alpine
    restart: always
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - letsencrypt-data:/etc/letsencrypt
      - /var/www/html:/var/www/html
    network_mode: host

  certbot:
    build:
      context: ./certbot
      args:
        - CLOUDFLARE_API_TOKEN
    environment:
      - DOMAIN=${DOMAIN}
      - WILDCARD_DOMAIN=${WILDCARD_DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - letsencrypt-data:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sh cert.sh; sleep 12h & wait $${!}; done;"
    # command: "certonly --agree-tos --dns-cloudflare --dns-cloudflare-credentials /.secrets/certbot/cloudflare.ini -m ${EMAIL} -d ${DOMAIN} -d ${WILDCARD_DOMAIN} -n"

volumes:
  letsencrypt-data:
  https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL
